repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: end-of-file-fixer
  - id: mixed-line-ending
    stages: [commit, push]
    args: [--fix=lf]
  - id: trailing-whitespace
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.21.2
  hooks:
  - id: commitizen
    stages: [commit-msg]
-   repo: local
    hooks:
    #Use dotnet format already installed on your machine
    -   id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format --include
        types_or: ["c#"]
